lista = ('SANTOS', 'CORINTHIAS', 'GREMIO', 'CHAPECOENCE','PALMEIRAS','CORITIBA','ATHLETICO' )
print('-=' * 20)
print(f'lista do campeonato: {lista} ')
print('-=' * 20)
print(f'OS 5 PRIMEIROS: {lista [0:5]}')
print('-=' * 20)
print(f'os 4 ultimos são {lista [-4:]}')
print('-=' * 20)
print(f'lista em ordem {sorted (lista)}')
print('-=' * 20)
print(f'Gremio esta em {lista.index("GREMIO")+1} posição')
